name: Integration tests

on:
  workflow_dispatch:
  push:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # note that these are not the requirements from the individual packages, but
        # the requirements from the repository root
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        make install-dev
    - name: Integration Test Diagnostics
      run: |
        v6 test integration-test --server-url http://172.17.0.1 --name integration-test --keep 1 --stop 0

